import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Sparkles, Lightbulb } from "lucide-react";

import { PageHeader } from "../../components/common/PageHeader";
import { GlassCard } from "../../components/common/GlassCard";
import { AIRecommendationCard } from "../../components/ai/AIRecommendationCard";
import { CardSkeleton, ErrorState, EmptyState } from "../../components/common/States";

import { recommendationService } from "../../services/aiService";

const PRIORITIES = ["all", "critical", "high", "medium", "low"];

export default function Recommendations() {
  const [priority, setPriority] = useState("all");
  const queryClient = useQueryClient();

  const recsQ = useQuery({
    queryKey: ["recommendations", priority],
    queryFn: () => recommendationService.list(priority === "all" ? {} : { priority }),
  });

  const refreshMutation = useMutation({
    mutationFn: recommendationService.refresh,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["recommendations"] }),
  });

  const statusMutation = useMutation({
    mutationFn: ({ id, status }) => recommendationService.updateStatus(id, status),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["recommendations"] }),
  });

  const rows = (recsQ.data || []).filter((r) => r.status === "open" || r.status === "in_progress");

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="AI ENGINE · RECOMMENDATIONS"
        title="Business Recommendation Engine"
        subtitle="Prioritized, AI-generated actions across outlets, inventory, staff, marketing, and audits."
        actions={
          <button
            onClick={() => refreshMutation.mutate()}
            disabled={refreshMutation.isPending}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium text-white bg-gradient-to-r from-blue-600 to-purple-600 shadow-md shadow-blue-500/25 disabled:opacity-60"
          >
            <Sparkles size={15} /> {refreshMutation.isPending ? "Refreshing..." : "Refresh Recommendations"}
          </button>
        }
      />

      <div className="flex gap-2">
        {PRIORITIES.map((p) => (
          <button key={p} onClick={() => setPriority(p)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium capitalize border transition-all ${
              priority === p
                ? "border-blue-300 bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:border-blue-500/30 dark:text-blue-400"
                : "border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400"
            }`}>
            {p}
          </button>
        ))}
      </div>

      <GlassCard className="p-5">
        <div className="flex items-center gap-2 mb-1">
          <Lightbulb size={16} className="text-blue-500" />
          <h2 className="font-semibold text-slate-900 dark:text-white">Open Recommendations</h2>
        </div>
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-4">
          Generated by the recommendation engine from live outlet, inventory, and audit data
        </p>

        {recsQ.isLoading ? (
          <CardSkeleton />
        ) : recsQ.isError ? (
          <ErrorState message="Couldn't load recommendations." onRetry={recsQ.refetch} />
        ) : rows.length === 0 ? (
          <EmptyState title="No recommendations yet" subtitle="Click 'Refresh Recommendations' to run the AI engine." />
        ) : (
          <div className="space-y-2.5">
            {rows.map((rec) => (
              <AIRecommendationCard
                key={rec.id}
                rec={rec}
                onStatusChange={(id, status) => statusMutation.mutate({ id, status })}
              />
            ))}
          </div>
        )}
      </GlassCard>
    </div>
  );
}
